"""add field length constraints

Revision ID: dcc546dbddcb
Revises: 1789f77a7a44
Create Date: 2026-09-18 01:09:27.735615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc546dbddcb'
down_revision: Union[str, Sequence[str], None] = '1789f77a7a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clientes",
        "nome",
        existing_type=sa.String(),
        type_=sa.String(length=100),
        existing_nullable=False
    )

    op.alter_column(
        "clientes",
        "email",
        existing_type=sa.String(),
        type_=sa.String(length=255),
        existing_nullable=False
    )

    op.alter_column(
        "clientes",
        "telefone",
        existing_type=sa.String(),
        type_=sa.String(length=20),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clientes",
        "nome",
        existing_type=sa.String(length=100),
        type_=sa.String(),
        existing_nullable=False
    )

    op.alter_column(
        "clientes",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.String(),
        existing_nullable=False
    )

    op.alter_column(
        "clientes",
        "telefone",
        existing_type=sa.String(length=20),
        type_=sa.String(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
